#!/bin/bash

SBT_VERSION=0.13

mkdir -p ~/.sbt/$SBT_VERSION
USER_FILE=~/.sbt/$SBT_VERSION/users.sbt

cat << EOF > $USER_FILE
credentials += Credentials("Artifactory Realm", "${MAVEN_PRIVATE_HOSTNAME}", "${MAVEN_PRIVATE_USERNAME}", "${MAVEN_PRIVATE_PASSWORD}")
EOF

#now that there are credentials, run the command they wanted
sbt "$@"
EXIT_CODE=$?

rm  $USER_FILE
exit $EXIT_CODE
